config/routes.rb
Shownotes::Application.routes.draw do
  resources :podcasts

  root :to => 'pages#home'

  match 'show' => 'pages#show', :as => :show
  match 'sandbox_podcasts' => 'pages#sandbox_podcasts', :as => :sandbox_podcasts
  match 'sandbox_feeds' => 'pages#sandbox_feeds', :as => :sandbox_feeds

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  attr_accessible :description, :image, :name, :url_itunes, :url_rss, :url_web

  def self.parse_feed(feed_url)
    Feedzirra::Feed.fetch_and_parse(feed_url)
  end

  def self.search_itunes(query)
    ITunesSearchAPI.search(:term => query, :country => "US", :media => "podcast", :attribute => "descriptionTerm")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @results = Podcast.search_itunes(params[:query])
  end
  def show
    @feedUrl = params[:url_rss]
    @url_itunes = params[:url_itunes]
    @podcast = Podcast.parse_feed(@feedUrl)
    respond_to do |format|
      format.js   { render :layout => false }
      format.html { redirect_to show_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @podcasts }
    end
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @podcast }
    end
  end

  # GET /podcasts/new
  # GET /podcasts/new.json
  def new
    @podcast = Podcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @podcast }
    end
  end

  # GET /podcasts/1/edit
  def edit
    @podcast = Podcast.find(params[:id])
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(params[:podcast])

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render json: @podcast, status: :created, location: @podcast }
      else
        format.html { render action: "new" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /podcasts/1
  # PUT /podcasts/1.json
  def update
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      if @podcast.update_attributes(params[:podcast])
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodCrawler // iTunes Podcast Search, Made Easy</title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>

  <!-- Meta For Viewport & Responsiveness -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  <!-- Touch Icon -->
  <link rel="apple-touch-icon" href="http://podcrawler.herokuapp.com/apple-touch-icon.png" />

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300' rel='stylesheet' type='text/css'>

</head>
<body>

<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40251915-4', 'podcrawler.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/pages/_episode.html.erb
      <li class="ep">
        <%= link_to(entry['enclosure_url']) do %>
          <p class="datetime">
            <span class="date"><%= entry.published.strftime("%b %e, %Y") %></span>
            <span class="time"><%= entry.published.strftime("%l:%M %p") %></span>
          </p> <!-- end: .datetime -->
          <h3><%= entry.title %></h3>
          <p class="play"><span></span></p>
        <% end %>
        <% unless entry['itunes_subtitle'].blank? %><p class="desc"><%= entry.itunes_subtitle %></p><% end %>
        <ul class="sub">
          <% unless entry['itunes_duration'].blank? %>
            <li class="l"><%= entry.itunes_duration %></li>
          <% end %>
          <% unless entry['url'].blank? %>
            <li class="r"><a href="<%= entry.url %>">View on Web</a></li>
          <% end %>
        </ul>
      </li>

app/views/pages/_feed.html.erb
    
    <% unless @feed.blank? %>
      
      <img width="200" src="<%= @feed.itunes_image %>" />
      <h2><%= @feed.title %></h2>
      <p><%= @feed.description %></p>
      <p>
        <% unless @feed.url.blank? %><a href="<%= @feed.url %>">Website</a><% end %>
        <% unless @feed.feed_url.blank? %><a href="<%= @feed.feed_url %>">RSS</a><% end %>
      </p>
    <% end %>
    <%# @entries.each do |entry| %>
    <% @feed.entries.each do |entry| %>
      <p>
        <span style="color: #aaa; font-size: 12px;"><%= entry.published.strftime("%b %e %y, %l:%M %p") %></span><br />
        <strong><%= entry.title %></strong><br />
        <% unless entry['itunes_duration'].blank? %><%= entry.itunes_duration %><br /><% end %>
        <% unless entry['itunes_subtitle'].blank? %><%= entry.itunes_subtitle %><br /><% end %>
        <% unless entry['enclosure_url'].blank? %><a href="<%= entry['enclosure_url'] %>">Listen</a><% end %> | <% unless entry['url'].blank? %><a href="<%= entry.url %>">Webpage</a><% end %>
      </p>
    <% end %>

app/views/pages/_podcast.html.erb
<div class="back-to">
  <p><a href="#">&larr; back to search results</a></p>
</div>

<div class="pod-wrap">

  <% unless @podcast.blank? %>

  <div class="pod-title">
    <p class="thumb">
      <img src="<%= @podcast.itunes_image %>" />
    </p>
    <h1><%= @podcast.title %></h1>
  </div> <!-- end: .pod-title -->

  <div class="pod-info">
    <h4>Podcast Links</h4>    
    <ul class="actions">
      <li><a href="<%= @url_itunes %>">iTunes</a></li>
      <li><a href="<%= @feedUrl %>">RSS</a></li>
      <li><a href="<%= @podcast.url %>">Website</a></li>
    </ul>
  </div> <!-- end: .pod-info -->

  <% unless @podcast.description.blank? %>
  <div class="pod-info">
    <h4>Podcast Description</h4>
    <p class="desc"><%= @podcast.description %></p>
  </div> <!-- end: .pod-info -->
  <% end %>

  <div class="ep-box">
    <h4>Latest Episode</h4>
    <ul class="eps">
      <% @podcast.entries[0..0].each_with_index do |entry,i| %>
        <%= render :partial => 'pages/episode', :locals => { :entry => entry } %>
      <% end %>
    </ul> <!-- end: .eps -->

    <h4>Past Episodes</h4>
    <ul class="eps">
      <% @podcast.entries[1..-1].each_with_index do |entry,i| %>
        <%= render :partial => 'pages/episode', :locals => { :entry => entry } %>
      <% end %>
    </ul> <!-- end: .eps -->
  </div> <!-- end: .ep-box -->
  
  <% end # unless @podcast.blank? %>

</div> <!-- end: .pod-wrap -->

app/views/pages/home.html.erb
<div class="side feeds">

  <div class="title-box">
    <div class="title-inner fadein">
      <h1><a href="/">PodCrawler</a></h1>
      <p>Search iTunes Podcasts, Fast!</p>
      <form method="get" action="/">
        <%= text_field_tag(:query, params[:query]) %>
        <span class="search-clear"></span>
        <%= submit_tag("", :id => "results-submit", :name => nil) %>
      </form>
    </div> <!-- end: title-inner -->
  </div> <!-- // .title-box -->

  <div class="feeds-wrap-inner fadein">

    <% unless params[:query].present? %>

      <div class="pre-search">
        <h4>Example searches</h4>
        <ul class="pills">
          <li><a class="sample-search">NPR</a></li>
          <li><a class="sample-search">comics</a></li>
          <li><a class="sample-search">startups</a></li>
          <li><a class="sample-search">Redskins</a></li>
          <li><a class="sample-search">sports</a></li>
          <li><a class="sample-search">NFL</a></li>
          <li><a class="sample-search">Brian Brushwood</a></li>
          <li><a class="sample-search">5by5</a></li>
          <li><a class="sample-search">Walking Dead</a></li>
          <li><a class="sample-search">yoga</a></li>
          <li><a class="sample-search">culture</a></li>
          <li><a class="sample-search">movies</a></li>
          <li><a class="sample-search">Arcade Fire</a></li>
          <li><a class="sample-search">Bill Simmons</a></li>
          <li><a class="sample-search">TWiT</a></li>
          <li><a class="sample-search">Nerdist</a></li>
          <li><a class="sample-search">responsive</a></li>
          <li><a class="sample-search">design</a></li>
          <li><a class="sample-search">Duncan Trussell</a></li>
          <li><a class="sample-search">Eastbound &amp; Down</a></li>
          <li><a class="sample-search">NHL</a></li>
        </ul>
        <h4>About</h4>
        <p>PodCrawler was designed &amp; built by <a href="http://davidpots.com">@davidpots</a> to help you find podcasts faster. We all know that searching for podcasts (or anything) on iTunes is a stinky experience, riddled with too many clicks and a bloated interface. PodCrawler solves that problem by getting straight to the point.</p>
        <p>If you like this tool, <a href="http://twitter.com/davidpots">follow me on Twitter</a> and also check out my <a href="http://songnotes.cc">Songnotes</a> project -- where I share my hand-crafted library of guitar tabs &amp; musical notation for songs I love.</p>
      </div> <!-- end: pre-search -->

    <% end %>

    <% @results.each do |result| %>
    <a class="feed" data-url-rss="<%= result['feedUrl'] %>" data-url-itunes="<%= result['trackViewUrl'] %>">
      <div class="thumbnail"><img src="<%= result['artworkUrl100'] %>" /></div>
      <div class="text">
        <h3><%= result['collectionName'] %></h3>
      </div>
    </a>
    <% end %>
  </div> <!-- // .feeds-wrap-inner -->

</div> <!-- // .side.feeds -->

<%# This is the hidden form that accepts an RSS feed, and displays that feed's info + entries on the page %>
<%= form_tag('/show', method: :get, :remote => true, :id => 'feed_select', :style => 'visibility: hidden;position: fixed;') do %>  
  <%= text_field_tag :url_rss, params[:url_rss] %>
  <%= hidden_field_tag :url_itunes, params[:url_itunes] %>
  <%= submit_tag("Search", :id => "submit") %>
<% end %>

<div class="main podcast_wrap_outer">
  <div class="spinner">
    <div class="spinner_inner_wrap">
      <p>
        <img width="66" src="/assets/spinner.gif" />
        <span>loading podcast...</span>
      </p>
    </div>
  </div>
  <div id="podcast_wrap_inner"></div>
</div>

app/views/pages/sandbox.html.erb
<div class="details-bg">
  <div class="back-to">
    <p><a href="#">&larr; back to search results</a></p>
  </div>

  <div class="pc-info">
    <p class="thumb">
      <img src="http://icebox.5by5.tv/images/broadcasts/47/cover.jpg" />
    </p>
    <h1>The Crossover</h1>
    <p class="desc">A weekly discussion featuring hosts from 5by5's many shows with no limit on topic or fixed agenda; a freeform flow of ideas leading to a great conversation, from culture to tech and beyond. Hosted by Dan Benjamin.</p>
    <ul class="actions">
      <li><a href="">iTunes</a></li>
      <li><a href="">RSS</a></li>
      <li><a href="">Podcast Website</a></li>
    </ul>
  </div> <!-- end: .pc-info -->

  <div class="ep-box">
    <h4>Most Recent Episode</h4>
    <ul class="eps">
      <% 1.times do %>
      <li class="ep">
        <div class="datetime">
          <span class="date">Sep 12, 2012</span>
          <span class="time">10:45 PM</span>
        </div> <!-- end: .date -->
        <div class="desc">
          <h3>5by5 Specials 8: The iPhone 5</h3>
          <p>Dan Benjamin is joined by Christina Warren, Marco Arment, John Siracusa, and Haddie Cooke to discuss Apple's iPhone 5 announcement.</p>
          <ul class="actions">
            <li><a href="http://d.5by5.net/redirect.mp3/fly.5by5.tv/audio/broadcasts/specials/2012/specials-008.mp3">Listen</a></li>
            <li><a href="http://5by5.tv/specials/8">Episode Webpage</a></li>
          </ul>
        </div> <!-- end: .desc -->
        <div class="player">
          
        </div> <!-- end: .player -->
      </li> <!-- end: .ep -->
      <% end %>
    </ul> <!-- end: .eps -->
  </div> <!-- end: .ep-box -->

  <div class="ep-box">
    <h4>Past Episodes</h4>
    <ul class="eps">
      <% 5.times do %>
      <li class="ep">
        <div class="datetime">
          <span class="date">Sep 12, 2012</span>
          <span class="time">10:45 PM</span>
        </div> <!-- end: .date -->
        <div class="desc">
          <h3>5by5 Specials 8: The iPhone 5</h3>
          <p>Dan Benjamin is joined by Christina Warren, Marco Arment, John Siracusa, and Haddie Cooke to discuss Apple's iPhone 5 announcement.</p>
          <ul class="actions">
            <li><a href="http://d.5by5.net/redirect.mp3/fly.5by5.tv/audio/broadcasts/specials/2012/specials-008.mp3">Listen</a></li>
            <li><a href="http://5by5.tv/specials/8">Episode Webpage</a></li>
          </ul>
        </div> <!-- end: .desc -->
        <div class="player">
          
        </div> <!-- end: .player -->
      </li> <!-- end: .ep -->
      <% end %>
    </ul>

  </div> <!-- end: .ep-box -->


</div> <!-- end: #podcast_wrap_inner-->

app/views/pages/sandbox_feeds.html.erb
<div class="side feeds">

  <div class="title-box">
    <h1>PodGnostic</h1>
    <p> The easiest way to search the <br />iTunes Podcast directory.</p>
    <form method="get" action="/">
      <%= text_field_tag(:query, params[:query]) %>
      <%= submit_tag("", :id => "results-submit", :name => nil) %>
    </form>
  </div> <!-- // .title-box -->

  <div class="feeds-wrap-inner">

  </div> <!-- // .feeds-wrap-inner -->

</div> <!-- // .side.feeds -->

app/views/pages/sandbox_podcasts.html.erb
<div class="details-bg">

  <div class="back-to">
    <p><a href="#">&larr; back to search results</a></p>
  </div>

  <div class="pod-info">
    <p class="thumb">
      <img src="http://icebox.5by5.tv/images/broadcasts/47/cover.jpg" />
    </p>
    <h1>The Crossover</h1>
    <p class="desc">A weekly discussion featuring hosts from 5by5's many shows with no limit on topic or fixed agenda; a freeform flow of ideas leading to a great conversation, from culture to tech and beyond. Hosted by Dan Benjamin.</p>
    <ul class="actions">
      <li><a href="">iTunes</a></li>
      <li><a href="">RSS</a></li>
      <li><a href="">Podcast Website</a></li>
    </ul>
  </div> <!-- end: .pod-info -->

  <div class="ep-box">
    <h4>Most Recent Episode</h4>
    <ul class="eps">
      <% 1.times do %>
      <li class="ep">
        <div class="datetime">
          <span class="date">Sep 12, 2012</span>
          <span class="time">10:45 PM</span>
        </div> <!-- end: .date -->
        <div class="desc">
          <h3>5by5 Specials 8: The iPhone 5</h3>
          <p>Dan Benjamin is joined by Christina Warren, Marco Arment, John Siracusa, and Haddie Cooke to discuss Apple's iPhone 5 announcement.</p>
          <ul class="actions">
            <li><a href="http://d.5by5.net/redirect.mp3/fly.5by5.tv/audio/broadcasts/specials/2012/specials-008.mp3">Listen</a></li>
            <li><a href="http://5by5.tv/specials/8">Episode Webpage</a></li>
          </ul>
        </div> <!-- end: .desc -->
        <div class="player">
          
        </div> <!-- end: .player -->
      </li> <!-- end: .ep -->
      <% end %>
    </ul> <!-- end: .eps -->
  </div> <!-- end: .ep-box -->

  <div class="ep-box">
    <h4>Past Episodes</h4>
    <ul class="eps">
      <% 5.times do %>
      <li class="ep">
        <div class="datetime">
          <span class="date">Sep 12, 2012</span>
          <span class="time">10:45 PM</span>
        </div> <!-- end: .date -->
        <div class="desc">
          <h3>5by5 Specials 8: The iPhone 5</h3>
          <p>Dan Benjamin is joined by Christina Warren, Marco Arment, John Siracusa, and Haddie Cooke to discuss Apple's iPhone 5 announcement.</p>
          <ul class="actions">
            <li><a href="http://d.5by5.net/redirect.mp3/fly.5by5.tv/audio/broadcasts/specials/2012/specials-008.mp3">Listen</a></li>
            <li><a href="http://5by5.tv/specials/8">Episode Webpage</a></li>
          </ul>
        </div> <!-- end: .desc -->
        <div class="player">
          
        </div> <!-- end: .player -->
      </li> <!-- end: .ep -->
      <% end %>
    </ul>

  </div> <!-- end: .ep-box -->

</div> <!-- end: .details-bg -->

app/views/pages/show.js.erb
// Initially I thought an event trigger was necessary to make this work,
// but in reality this was forcing me to submit the form an additional time.
// By using the 'document.ready()' alone, as shown below, it works!
//
// $('#feed_select').bind('submit', function() {
// $(document).on('submit', '#feed_select', function(){

$(document).ready(function(){
  $("#podcast_wrap_inner").html("<%= escape_javascript(render(:partial => 'pages/podcast')) %>");
  i = i+1;
  window.location.hash = "url=<%= @url_itunes %>&key="+i;
  $(".spinner").hide();

   $('img').error(function () {
      $(this).addClass('error');
  });

});

app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :url_web %><br />
    <%= f.text_field :url_web %>
  </div>
  <div class="field">
    <%= f.label :url_rss %><br />
    <%= f.text_field :url_rss %>
  </div>
  <div class="field">
    <%= f.label :url_itunes %><br />
    <%= f.text_field :url_itunes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<h1>Listing podcasts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Url web</th>
    <th>Url rss</th>
    <th>Url itunes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @podcasts.each do |podcast| %>
  <tr>
    <td><%= podcast.name %></td>
    <td><%= podcast.description %></td>
    <td><%= podcast.image %></td>
    <td><%= podcast.url_web %></td>
    <td><%= podcast.url_rss %></td>
    <td><%= podcast.url_itunes %></td>
    <td><%= link_to 'Show', podcast %></td>
    <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>
    <td><%= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Podcast', new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @podcast.name %>
</p>

<p>
  <b>Description:</b>
  <%= @podcast.description %>
</p>

<p>
  <b>Image:</b>
  <%= @podcast.image %>
</p>

<p>
  <b>Url web:</b>
  <%= @podcast.url_web %>
</p>

<p>
  <b>Url rss:</b>
  <%= @podcast.url_rss %>
</p>

<p>
  <b>Url itunes:</b>
  <%= @podcast.url_itunes %>
</p>


<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>